name: ReleasePreview

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

  # ensure only one PRTest check runs at a time
concurrency:
  group: prtest
  cancel-in-progress: true

jobs:
  Changes:
      
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.filter.outputs.changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Changes Filter
        id: filter
        uses: ./.github/actions/changes-filter

  PreviewBuild:
    runs-on: ubuntu-latest
    
    needs: [Changes]
    
    # only run on pull requests created by release please
    # this means:
    # creator is github-actions
    # base branch is master
    # the branch name is release-please--branches-master
    if: ${{ needs.Changes.outputs.changed.go == 'true' && github.actor == 'github-actions' && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'release-please--branches-master' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup jetpack devbox
        uses: jetpack-io/devbox-install-action@v0.7.0

      - name: Build  
        run: devbox run -- just preview

      - name: Upload Artifacts
        uses: airtonix/upload-artifact@artifact-per-file
        with:
          artifact-per-file: true
          path: dist/**/*

      - uses: beni69/artifact-link@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}