name: PR Checks

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  DetectCheckboxes:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
    steps:
      - uses: marocchino/checkbox-action@83deaedb2f6c61664cccd3f433984e210acbe304
        id: detect
        with:
          action: 'detect'

  PrintCheckboxes:
    needs: DetectCheckboxes
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{needs.detect.outputs.checked}}

  LintPrTitle:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  LintAndTest:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: OS Deps
        uses: ./.github/actions/setup-os
      
      # Just let ASDF do its thing. It's far easier and more reliable than trying to do it ourselves.
      - name: Tooling
        uses: ./.github/actions/setup-tooling
        with:
          SetupCommand: ./setup.sh
      - name: Format
        run: just lint