name: PR Checks

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  # DetectCheckboxes:
  #   runs-on: ubuntu-22.04
  #   outputs:
  #     checked: ${{ steps.detect.outputs.checked }}

  #   if: ${{ !github.event.act }}

  #   steps:
  #     - uses: marocchino/checkbox-action@83deaedb2f6c61664cccd3f433984e210acbe304
  #       id: detect
  #       with:
  #         action: 'detect'

  # PrintCheckboxes:
  #   needs: DetectCheckboxes
  #   runs-on: ubuntu-22.04

  #   if: ${{ !github.event.act }}

  #   steps:
  #     - run: |
  #         echo ${{needs.detect.outputs.checked}}

  LintPrTitle:
    runs-on: ubuntu-22.04
    permissions:
      statuses: write

    if: ${{ !github.event.act }}

    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  LintAndTest:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: setup jetpack devbox
        uses: jetpack-io/devbox-install-action@v0.7.0
      
      - name: add problem matcher
        run: |
          echo "##[add-matcher]./.github/problem-matcher.json"

      - name: Lint
        run: devbox run -- just lint

      - name: Test
        run: devbox run -- just test

      - name: Build
        run: devbox run -- just build

      - uses: actions/upload-artifact@v3
        with:
          path: |
            dist/**/*
            !dist/**/*.json
            !dist/**/*.yaml

      - name: Post comment to pull request with its artifacts
        uses: montogeek/github-action-comment-artifacts@1.0